trigger:
- master

queue:
  name: Hosted VS2017
  demands: npm

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '8.10'
  displayName: 'Instalando o Node.js'

- script: |
    npm install -g @angular/cli
    npm install
  displayName: 'Instalando Dependências'

- task: Npm@1
  displayName: 'Buildando Projeto Luxfacta'
  inputs:
    verbose: false
- script: 'npm run build:ssr'
  displayName: 'Buildando o projeto Luxfacta'

- task: CopyFiles@2
  displayName: 'Copiando a dist'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)/dist'
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app/dist'

- task: CopyFiles@2
  displayName: 'Copiando server.js para a raiz'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/app/dist'
    Contents: server.js
    TargetFolder: '$(Build.ArtifactStagingDirectory)/app'

- task: DeleteFiles@1
  displayName: 'Deletando dist/server.js'
  inputs:
    SourceFolder: '$(Build.ArtifactStagingDirectory)/app/dist'
    Contents: server.js

- task: AzureRmWebAppDeployment@3
  displayName: 'Azure App Service Deploy: siteClimarq'
  inputs:
    azureSubscription: 'Pago pelo Uso (7269176a-08c5-4145-a223-b198c639d03c)'
    WebAppName: 'siteClimarq'
    DeployToSlotFlag: true
    ResourceGroupName: 'Climarqwork'
    Package: '$(Build.ArtifactStagingDirectory)/app'
    GenerateWebConfig: true
    WebConfigParameters: '-Handler iisnode -NodeStartFile server.js -appType node'
    UseWebDeploy: true
    RemoveAdditionalFilesFlag: true
